# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on:
    # Sequence of patterns matched against refs/tags
    push:
      branches:
        - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14.0.2
      uses: actions/setup-java@v1.4.2
      with:
        java-version: '14.0.2'
        java-package: jdk+fx
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Package with Gradle
      run: ./gradlew jpackage
    - name: list directory *nix
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      run: |
        ls -al
    - name: list directory win
      if: matrix.os == 'windows-latest'
      run: |
        dir
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-jpackage
        path: |
          build/jpackage
          !build/jpackage/labirintoa/bin
          !build/jpackage/labirintoa/lib
